services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ecomerce-api
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: "redis:latest"
    container_name: "redis_ecomerce"
    ports:
      - "6379:6379"
    networks:
      - cache-network

networks:
  cache-network:
    driver: bridge
    
volumes:
  db_data:
    driver: local
